### PR TITLE
Fix ts compile errors

### LINKED ISSUE #299: Fix TypeScript compile errors
Creating #288 I have realized that we have 28 errors in 10 files:

```
Errors  Files
     3  nuxt.config.ts:27
     3  services/course.ts:41
     1  services/unit.ts:23
     1  services/user.ts:33
     2  services/utils.ts:12
     3  store/course/store.ts:45
     1  store/unit/store.ts:39
     1  store/user/store.ts:72
     7  store/utils.ts:4
     6  tests/widgets/components/binary/index.test.ts:6
```

### PR DESCRIPTION
**Pull request by y4izus**
## Changes

  Closes #299 

## Implementation details

I've fixed each file on different commits. Hope this help with the review

### CODE REVIEW

File: store/utils.ts [hunk 1]
```diff
@@ -1,27 +1,31 @@
...
+): T {
   return {
     ...filterUndefinedObjectKeys(base),
     ...filterUndefinedObjectKeys(overriding),
   };
 }
 
-// eslint-disable-next-line @typescript-eslint/ban-types
-export function filterUndefinedObjectKeys<T extends Object>(original: T): T {
+export function filterUndefinedObjectKeys<T extends Record<string, any>>(
```
Comment (Tansito) [inline store/utils.ts:13]: I touched this method in other PR and I left this method and `addObjectInfoToList` like here:

https://github.com/Qiskit/saiba/pull/294/files#diff-0794f9cb19281f2aea03d998f4c8b246f7e344bec11d64206a2e230f821e07adR10-R11

Overall I prefer this approach instead of `Record` because we are expecting an `Object` there and `Record` it's not exactly that I think, but I'm totally open to other opinions: @abdonrd , @korgan00 , @yoshiemuranaka ?

File: store/utils.ts [hunk 2]
```diff
@@ -1,27 +1,31 @@
...
+): T {
   const target = { ...original };
   Object.keys(target).forEach(
     (key) => target[key] === undefined && delete target[key]
   );
   return target;
 }
 
-export function addObjectInfoToList<T>(
+export function addObjectInfoToList<T extends Record<string, any>>(
```
Comment (Tansito) [inline store/utils.ts:23]: Similar to my previous comment in `filterUndefinedObjectKeys`.

File: tests/widgets/components/binary/index.test.ts [hunk 3]
```diff
@@ -1,18 +1,16 @@
-import { describe, it, expect, beforeEach } from 'vitest';
+import { describe, it, expect } from 'vitest';
 import { shallowMount } from '@vue/test-utils';
 import Binary from '../../../../widgets/components/binary/index.vue';
 
 describe('Binary widget', () => {
-  let wrapper;
-  beforeEach(() => {
```
Comment (abdonrd) [inline tests/widgets/components/binary/index.test.ts:7]: No idea about the implications of remove the `beforeEach`.

File: store/unit/store.ts [hunk 4]
```diff
@@ -36,7 +36,7 @@ export const useUnitStore = defineStore('unitStore', () => {
   }
 
   function setActiveUnitIdBySlug(unitSlug: Unit['slug']) {
-    activeUnitId.value = unitBySlug(unitSlug).value?.id;
+    activeUnitId.value = unitBySlug(unitSlug).value?.id || '';
```
Comment (abdonrd) [inline store/unit/store.ts:39]: Is right to assign an empty value to the `activeUnitId`? Or just avoid to change the value?

```suggestion
    const unit = unitBySlug(unitSlug);
    if (unit.value) {
      activeUnitId.value = unit.value.id;
    }
```

File: store/utils.ts (hunk 1 above)
Comment (abdonrd) [reply store/utils.ts:13]: I have always used [index signatures](https://www.typescriptlang.org/docs/handbook/2/objects.html#index-signatures) like `{ [key: string]: any }`, but I don't know if now `Record` is a better option.

Comment (abdonrd) [reply store/utils.ts:13]: https://stackoverflow.com/posts/54100359/revisions

**Review by abdonrd — CHANGES_REQUESTED** [review]

**Comment by abdonrd** [comment]
By the way, thanks for work on this! 👏🏻

File: nuxt.config.ts [hunk 5]
```diff
@@ -22,9 +22,12 @@ export default defineNuxtConfig({
   buildModules: ['@pinia/nuxt'],
```
[the remark this answers is not in the document]
Comment (abdonrd) [reply nuxt.config.ts:22]: You can merge this https://github.com/Qiskit/saiba/pull/288 instead of `main` to check it.

File: store/utils.ts (hunk 1 above)
Comment (y4izus) [reply store/utils.ts:13]: I've used `Record` because [I saw it on the docs](https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeys-type), but I don't have a strong opinion here

File: tests/widgets/components/binary/index.test.ts (hunk 3 above)
Comment (y4izus) [reply tests/widgets/components/binary/index.test.ts:7]: I've removed because it's not needed here and it solves the problem. We can ask Randy (he did this test) if it's ok if we remove it

File: nuxt.config.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (y4izus) [reply nuxt.config.ts:22]: I checked it executing `npm run lint:tsc`, but I'm not having this error. Maybe we can check this together to find out what is happening

File: services/course.ts [hunk 6]
```diff
@@ -37,9 +37,11 @@ export const getCourse = (courseId: string, lang = 'en-US') => {
...
   };
 
-  return $fetch(getGraphQLURL(), gqlQueryOptions(query, queryVariables)).then(
-    (res: Query<CourseListDTO>) => res.data.courses[0]
-  );
+  return (
+    $fetch(getGraphQLURL(), gqlQueryOptions(query, queryVariables)) as Promise<
+      Query<CourseListDTO>
+    >
+  ).then((res: Query<CourseListDTO>) => res.data.courses[0]);
```
[the remark this answers is not in the document]
Comment (y4izus) [reply services/course.ts]: Done in:
- https://github.com/Qiskit/saiba/pull/324/commits/fe1e8cfa548bcd21dd6b6eebdc6614ad4b851c46
- https://github.com/Qiskit/saiba/pull/324/commits/f7ce20904995859273c43545187e0a0f4849e400
- https://github.com/Qiskit/saiba/pull/324/commits/f3dce7e92a9b6a7684e2865a851126e2d3789dc9

File: store/unit/store.ts (hunk 4 above)
Comment (y4izus) [reply store/unit/store.ts:39]: I think it's right assign an empty value. `''` is the default value and if we have a unit for which we don't find the `id`, I think we should have `''` instead of the previous value.
I can be wrong, so let's ask @Tansito and @korgan00 , just in case I'm missing something

Comment (Tansito) [reply store/unit/store.ts:39]: I understand why we are using the **default value** but for me it's weird that the default value is an **empty string**. I don't know if there is a reason behind but I would say `null` or `undefined` would be better values.

File: store/utils.ts (hunk 1 above)
Comment (korgan00) [reply store/utils.ts:13]: I prefer the index signatures too

File: store/unit/store.ts (hunk 4 above)
Comment (korgan00) [reply store/unit/store.ts:39]: I fine with extending type to null or undefined but I don't have strong opinions here.

File: nuxt.config.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (abdonrd) [reply nuxt.config.ts:22]: I think it was my problem for going to change branches. Forget it!

File: store/utils.ts (hunk 1 above)
Comment (abdonrd) [reply store/utils.ts:13]: Reading this I assume the index signatures fit better for this case:
https://stackoverflow.com/questions/54100025/difference-between-index-signature-and-record-for-empty-object/54100359#54100359

File: tests/widgets/components/binary/index.test.ts (hunk 3 above)
Comment (techtolentino) [reply tests/widgets/components/binary/index.test.ts:7]: LGTM, thank you 👏🏼

File: store/unit/store.ts (hunk 4 above)
Comment (y4izus) [reply store/unit/store.ts]: Done https://github.com/Qiskit/saiba/pull/324/commits/714bd0c044137c2f4e3771301e923a32ec7211df

**Review by Tansito — APPROVED** [review]
Thanks a lot for this @y4izus 💯
